// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArSRugEfLZw8cZu8jn___L6N7nvDUY36M',
    appId: '1:539719533651:web:7e57470d5f5b74b8a572a6',
    messagingSenderId: '539719533651',
    projectId: 'giscustomer',
    authDomain: 'giscustomer.firebaseapp.com',
    databaseURL: 'https://giscustomer-default-rtdb.firebaseio.com',
    storageBucket: 'giscustomer.appspot.com',
    measurementId: 'G-FRJ9F8YTSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTVP2KfoJPtrsCLDJTJsG8_lcyXa88zUo',
    appId: '1:539719533651:android:6810df70b2ac2432a572a6',
    messagingSenderId: '539719533651',
    projectId: 'giscustomer',
    databaseURL: 'https://giscustomer-default-rtdb.firebaseio.com',
    storageBucket: 'giscustomer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCncXFm46vvyrAKHfo82OKqUkyfLEAJN8Q',
    appId: '1:539719533651:ios:b9f0e39d1e3af562a572a6',
    messagingSenderId: '539719533651',
    projectId: 'giscustomer',
    databaseURL: 'https://giscustomer-default-rtdb.firebaseio.com',
    storageBucket: 'giscustomer.appspot.com',
    iosBundleId: 'com.example.testFirebase',
  );
}
